# ===================================================================
# 운영 서버(Production) 전용 Docker Compose 파일 - AWS RDS 사용
# ===================================================================
services:
  app:
    image: dvrpcsh/subdivision-prj:latest
    container_name: subdivision-app
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - ./.env

  redis:
    image: redis:latest
    container_name: subdivision-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  redis-data: